name: Update words list
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "20 12 * * 0"

jobs:
  update_words_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.43.5"
      - name: Update words list
        run: deno run --allow-net --allow-write pedantix_mots.ts
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              mots.txt
              mots_sans_stopwords.txt
            commit-msg: Update words list
            github-token: ${{ secrets.GITHUB_TOKEN }}  
